name: Deploy Quarto Site

on:
  push:
    branches:
      - GH_Pages  # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        run: |
          wget -qO quarto.deb https://quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto.deb

      - name: Render Quarto Site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Deploy the _site folder
