project:
  type: website

website:
  title: "The Marketing Scientist"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: articles.qmd
        text: Articles
  page-navigation: true

format:
  html:
    theme: cosmo
