project:
  type: website

website:
  title: "The Marketing Scientist"
  site-url: "https://TheMarketingScientist.github.io/themarketingscientist-ai"
  repo-url: "https://github.com/TheMarketingScientist/themarketingscientist-ai"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: articles.qmd
        text: Articles
  page-navigation: true
  search: true  # Enables built-in search

format:
  html:
    theme: cosmo
    css: styles.css  # Optional custom CSS
    toc: true  # Enables table of contents

execute:
  enabled: true
  freeze: auto  # Ensures cells are re-run when content changes
  cache: true  # Speeds up rendering by caching outputs

metadata-files:
  - _authors.yml  # Optional author metadata
  - _bibliography.yml  # Optional references

resources:
  - CNAME  # If using a custom domain

editor: visual
