project:
  type: website
website:
  title: "The Marketing Scientist"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: articles.qmd  # Ensure it's listed here
        text: Articles
format:
  html:
    theme: cosmo
