name: Deploy Quarto Site

on:
  push:
    branches:
      - GH_Pages  # Runs when you push to GH_Pages

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GH_Pages branch
        uses: actions/checkout@v4
        with:
          ref: GH_Pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site  # Deploys the pre-rendered site
          publish_branch: gh-pages
