name: Deploy Quarto Site

on:
  push:
    branches:
      - GH_Pages  # Trigger deployment when changes are pushed to GH_Pages

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full git history for branch switching

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Check if _site exists
        run: |
          if [ ! -d "_site" ]; then
            echo "⚠️ _site directory not found. Exiting."
            exit 0
          fi

      - name: Move _site contents to root
        run: |
          rm -rf *  # Remove existing files in gh-pages
          cp -r _site/* .
          rm -rf _site  # Cleanup _site folder after copying

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Automated deployment from GH_Pages to gh-pages" || echo "No changes to commit"
          git push origin gh-pages
