name: Deploy Quarto Site

on:
  push:
    branches:
      - GH_Pages  # Runs when you push to GH_Pages

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0  # Ensure we get the full history

      - name: Backup existing static files
        run: |
          mkdir -p backup
          cp -r index.html backup/ || true
          cp -r CNAME backup/ || true
          cp -r *.jpg backup/ || true
          cp -r *.png backup/ || true
          cp -r *.svg backup/ || true
          cp -r *.ico backup/ || true
          cp -r style.css backup/ || true

      - name: Checkout GH_Pages branch
        uses: actions/checkout@v4
        with:
          ref: GH_Pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site  # Deploys the pre-rendered site
          publish_branch: gh-pages
          keep_files: true  # Keeps existing files instead of wiping everything

      - name: Restore preserved static files
        run: |
          cp -r backup/* . || true  # Restore all backed-up files
          rm -rf backup  # Cleanup backup folder

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Preserve static files while updating articles" || echo "No changes to commit"
          git push origin gh-pages
